INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('flint', 'Flint & Steel', 20, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('fireplace', 'Fireplace', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('tent_1', 'Tent', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('tent_2', 'Big Tent', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('wood', 'Wood', 30, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('chair_1', 'Chair', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('chair_2', 'Chair', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('chair_3', 'Chair', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('raw_chicken', 'Raw chicken', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('cooked_chicken', 'Cooked chicken', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('gazebo_1', 'Gazebo Black', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('gazebo_2', 'Gazebo Blue', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES ('gazebo_3', 'Gazebo White', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('beerkeg', 'Beer Keg - 30L - Full', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('beerkeg_2_3', 'Beer Keg - 30L - 2/3', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('beerkeg_1_3', 'Beer Keg - 30L - 1/3', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('beerkeg_0_3', 'Beer Keg - 30L - Empty', 5, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('beer_05', 'Beer 0.5l', 10, '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('beer_03', 'Beer 0.3l', 10, '0', '1');
