QBShared.Items = {
    --rcore_camping
    ['flint'] = { ['name'] = 'flint', ['label'] = 'Flint & Steel', ['weight'] = 500, ['type'] = 'item', ['image'] = 'flint.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Flint & Steel used for starting fire' },
    ['fireplace'] = { ['name'] = 'fireplace', ['label'] = 'Fireplace', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'fireplace.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Fireplace' },
    ['tent_1'] = { ['name'] = 'tent_1', ['label'] = 'Tent', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'tent.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Tent' },
    ['tent_2'] = { ['name'] = 'tent_2', ['label'] = 'Big Tent', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'tent.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Tent' },
    ['wood'] = { ['name'] = 'wood', ['label'] = 'Wood', ['weight'] = 500, ['type'] = 'item', ['image'] = 'wood.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Wood for fireplace' },
    ['chair_1'] = { ['name'] = 'chair_1', ['label'] = 'Chair', ['weight'] = 500, ['type'] = 'item', ['image'] = 'chair_1.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Chair' },
    ['chair_2'] = { ['name'] = 'chair_2', ['label'] = 'Chair', ['weight'] = 500, ['type'] = 'item', ['image'] = 'chair_2.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Chair' },
    ['chair_3'] = { ['name'] = 'chair_3', ['label'] = 'Chair', ['weight'] = 500, ['type'] = 'item', ['image'] = 'chair_3.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Chair' },
    ['gazebo_1'] = { ['name'] = 'tent_2', ['label'] = 'Gazebo Black', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'gazebo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Gazebo' },
    ['gazebo_2'] = { ['name'] = 'tent_2', ['label'] = 'Gazebo Blue', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'gazebo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Gazebo' },
    ['gazebo_3'] = { ['name'] = 'tent_2', ['label'] = 'Gazebo White', ['weight'] = 1000, ['type'] = 'item', ['image'] = 'gazebo.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Gazebo' },
    ['beerkeg'] = { ['name'] = 'beerkeg', ['label'] = 'Beer Keg - 30L- Full', ['weight'] = 750, ['type'] = 'item', ['image'] = 'beerkeg.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Beer keg with lot of beers!' },
    ['beerkeg_2_3'] = { ['name'] = 'beerkeg_2_3', ['label'] = 'Beer Keg - 30L - 2/3', ['weight'] = 750, ['type'] = 'item', ['image'] = 'beerkeg.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Beer keg with lot of beers!' },
    ['beerkeg_1_3'] = { ['name'] = 'beerkeg_1_3', ['label'] = 'Beer Keg - 30L- 1/3', ['weight'] = 750, ['type'] = 'item', ['image'] = 'beerkeg.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Beer keg with lot of beers!' },
    ['beerkeg_0_3'] = { ['name'] = 'beerkeg_0_3', ['label'] = 'Beer Keg - 30L - Empty', ['weight'] = 750, ['type'] = 'item', ['image'] = 'beerkeg.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Beer keg with lot of beers!' },
    ['beer_05'] = { ['name'] = 'beer_05', ['label'] = 'Beer 0.5l', ['weight'] = 750, ['type'] = 'item', ['image'] = 'beer_05.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Good size of beer glass!' },
    ['beer_03'] = { ['name'] = 'beer_03', ['label'] = 'Beer 0.3l', ['weight'] = 750, ['type'] = 'item', ['image'] = 'beer_03.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Smaller but still, good beer!' },
    --rcore_camping cooking
    ['raw_chicken'] = { ['name'] = 'raw_chicken', ['label'] = 'Raw chicken', ['weight'] = 500, ['type'] = 'item', ['image'] = 'raw_chicken.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['description'] = 'Raw chicken can be cooked on fire' },
    ['cooked_chicken'] = { ['name'] = 'cooked_chicken', ['label'] = 'Cooked chicken', ['weight'] = 500, ['type'] = 'item', ['image'] = 'cooked_chicken.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['description'] = 'Can be eaten' },
}
