CREATE TABLE IF NOT EXISTS `miki_shops` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `MarketName` longtext DEFAULT NULL,
  `MarketOwner` longtext DEFAULT NULL,
  `MarketOwnerName` longtext DEFAULT NULL,
  `Price` longtext DEFAULT '0',
  `image` longtext DEFAULT NULL,
  `description` longtext DEFAULT 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.',
  `renttime` longtext DEFAULT NULL,
  `totalearn` longtext DEFAULT '0',
  `money` longtext DEFAULT '0',
  `items` longtext DEFAULT '{}',
  `workers` longtext DEFAULT '{}',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;


INSERT INTO `miki_shops` (`id`, `MarketName`, `MarketOwner`, `MarketOwnerName`, `Price`, `image`, `description`, `renttime`, `totalearn`, `money`, `items`, `workers`) VALUES
	(1, 'Market 1', NULL, NULL, '75000', './img/markets/market1.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(2, 'Market 2', NULL, NULL, '65000', './img/markets/market2.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(3, 'Market 3', NULL, NULL, '98500', './img/markets/market3.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(4, 'Market 4', NULL, NULL, '63750', './img/markets/market4.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(5, 'Market 5', NULL, NULL, '17500', './img/markets/market5.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(6, 'Market 6', NULL, NULL, '23500', './img/markets/market6.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(7, 'Market 7', NULL, NULL, '23650', './img/markets/market7.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(8, 'Market 8', NULL, NULL, '12368', './img/markets/market8.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(9, 'Market 9', NULL, NULL, '12685', './img/markets/market9.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(10, 'Market 10', NULL, NULL, '18950', './img/markets/market10.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(11, 'Market 11', NULL, NULL, '13680', './img/markets/market11.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(12, 'Market 12', NULL, NULL, '23000', './img/markets/market12.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(13, 'Market 13', NULL, NULL, '35800', './img/markets/market13.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(14, 'Market 14', NULL, NULL, '42300', './img/markets/market14.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(15, 'Market 15', NULL, NULL, '23500', './img/markets/market15.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(16, 'Market 16', NULL, NULL, '24900', './img/markets/market16.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(17, 'Market 17', NULL, NULL, '26800', './img/markets/market17.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(18, 'Market 18', NULL, NULL, '32000', './img/markets/market18.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(19, 'Market 19', NULL, NULL, '23000', './img/markets/market19.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}'),
	(20, 'Market 20', NULL, NULL, '26800', './img/markets/market20.png', 'Renting a market space can be a strategic step for entrepreneurs looking to establish a retail presence without the commitment of a permanent location. This approach offers increased visibility, cost-efficiency, and flexibility, making it ideal for testing business ideas, attracting customers, and adapting to changing market dynamics. To succeed in this venture, select your market location wisely, create an appealing display, align with peak market days, network with fellow vendors, and actively promote your presence. With the right approach, renting a market space can pave the way to a successful and thriving business.', NULL, '0', '0', '{}', '{}');
