print("^2Jim^7-^2Chairs ^7v^41^7.^43 ^7- ^2Portable Chair Script by Jimathy^7")

-- Did I do a good job? Consider donating as this took me a long time to make for free.

-- If you need support I now have a discord available, it helps me keep track of issues and give better support.
-- https://discord.gg/xKgQZ6wZvS


Config = {
	Debug = false, 	 -- Enable this to help debug the script
	JimShops = true, -- Set to true if using jim-shops
	Notify = "qb",

	ExploitDistance = 1.2,  -- Default '1.2'.
							-- This is how close the person needs to be to the floor so they can use chairs
							-- Standing/sitting on vehicles isn't classed as the ground so you may want to raise this to between 5-6
							-- The higher the number, the more chance people have of exploiting no fall damage

	MakeStores = true,  	-- Enable if you want built in stores and locations
	Stores = {
		{	label = "Sandalye Dünyası",
			slots = 110,
			items = {
				{ name = "chair1", price = 0, amount = 50, info = {}, type = "item", slot = 1, },
				{ name = "chair2", price = 0, amount = 50, info = {}, type = "item", slot = 2, },
				{ name = "chair3", price = 0, amount = 50, info = {}, type = "item", slot = 3, },
				{ name = "chair4", price = 0, amount = 50, info = {}, type = "item", slot = 4, },
				{ name = "chair5", price = 0, amount = 50, info = {}, type = "item", slot = 5, },
				{ name = "chair6", price = 0, amount = 50, info = {}, type = "item", slot = 6, },
				{ name = "chair7", price = 0, amount = 50, info = {}, type = "item", slot = 7, },
				{ name = "chair8", price = 0, amount = 50, info = {}, type = "item", slot = 8, },
				{ name = "chair9", price = 0, amount = 50, info = {}, type = "item", slot = 9, },
				{ name = "chair10", price = 0, amount = 50, info = {}, type = "item", slot = 10, },
				{ name = "chair11", price = 0, amount = 50, info = {}, type = "item", slot = 11, },
				{ name = "chair12", price = 0, amount = 50, info = {}, type = "item", slot = 12, },
				{ name = "chair13", price = 0, amount = 50, info = {}, type = "item", slot = 13, },
				{ name = "chair14", price = 0, amount = 50, info = {}, type = "item", slot = 14, },
				{ name = "chair15", price = 0, amount = 50, info = {}, type = "item", slot = 15, },
				{ name = "chair16", price = 0, amount = 50, info = {}, type = "item", slot = 16, },
				{ name = "chair17", price = 0, amount = 50, info = {}, type = "item", slot = 17, },
				{ name = "chair18", price = 0, amount = 50, info = {}, type = "item", slot = 18, },
				{ name = "chair19", price = 0, amount = 50, info = {}, type = "item", slot = 19, },
				{ name = "chair20", price = 0, amount = 50, info = {}, type = "item", slot = 20, },
				{ name = "chair21", price = 0, amount = 50, info = {}, type = "item", slot = 21, },
				{ name = "chair22", price = 0, amount = 50, info = {}, type = "item", slot = 22, },
				{ name = "chair23", price = 0, amount = 50, info = {}, type = "item", slot = 23, },
				{ name = "chair24", price = 0, amount = 50, info = {}, type = "item", slot = 24, },
				{ name = "chair25", price = 0, amount = 50, info = {}, type = "item", slot = 25, },
				{ name = "chair26", price = 0, amount = 50, info = {}, type = "item", slot = 26, },
				{ name = "chair27", price = 0, amount = 50, info = {}, type = "item", slot = 27, },
				{ name = "chair28", price = 0, amount = 50, info = {}, type = "item", slot = 28, },
				{ name = "chair29", price = 0, amount = 50, info = {}, type = "item", slot = 29, },
				{ name = "chair30", price = 0, amount = 50, info = {}, type = "item", slot = 30, },
				{ name = "chair31", price = 0, amount = 50, info = {}, type = "item", slot = 31, },
				{ name = "chair32", price = 0, amount = 50, info = {}, type = "item", slot = 32, },
				{ name = "chair33", price = 0, amount = 50, info = {}, type = "item", slot = 33, },
				{ name = "chair34", price = 0, amount = 50, info = {}, type = "item", slot = 34, },
				{ name = "chair35", price = 0, amount = 50, info = {}, type = "item", slot = 35, },
				{ name = "chair36", price = 0, amount = 50, info = {}, type = "item", slot = 36, },
				{ name = "chair37", price = 0, amount = 50, info = {}, type = "item", slot = 37, },
				{ name = "chair38", price = 0, amount = 50, info = {}, type = "item", slot = 38, },
				{ name = "chair39", price = 0, amount = 50, info = {}, type = "item", slot = 39, },
				{ name = "chair40", price = 0, amount = 50, info = {}, type = "item", slot = 40, },
				{ name = "chair41", price = 0, amount = 50, info = {}, type = "item", slot = 41, },
				{ name = "chair42", price = 0, amount = 50, info = {}, type = "item", slot = 42, },
				{ name = "chair43", price = 0, amount = 50, info = {}, type = "item", slot = 43, },
				{ name = "chair44", price = 0, amount = 50, info = {}, type = "item", slot = 44, },
				{ name = "chair45", price = 0, amount = 50, info = {}, type = "item", slot = 45, },
				{ name = "chair46", price = 0, amount = 50, info = {}, type = "item", slot = 46, },
				{ name = "chair47", price = 0, amount = 50, info = {}, type = "item", slot = 47, },
				{ name = "chair48", price = 0, amount = 50, info = {}, type = "item", slot = 48, },
				{ name = "chair49", price = 0, amount = 50, info = {}, type = "item", slot = 49, },
				{ name = "chair50", price = 0, amount = 50, info = {}, type = "item", slot = 50, },
				{ name = "chair51", price = 0, amount = 50, info = {}, type = "item", slot = 51, },
				{ name = "chair52", price = 0, amount = 50, info = {}, type = "item", slot = 52, },
				{ name = "chair53", price = 0, amount = 50, info = {}, type = "item", slot = 53, },
				{ name = "chair54", price = 0, amount = 50, info = {}, type = "item", slot = 54, },
				{ name = "chair55", price = 0, amount = 50, info = {}, type = "item", slot = 55, },
				{ name = "chair56", price = 0, amount = 50, info = {}, type = "item", slot = 56, },
				{ name = "chair57", price = 0, amount = 50, info = {}, type = "item", slot = 57, },
				{ name = "chair58", price = 0, amount = 50, info = {}, type = "item", slot = 58, },
				{ name = "chair59", price = 0, amount = 50, info = {}, type = "item", slot = 59, },
				{ name = "chair60", price = 0, amount = 50, info = {}, type = "item", slot = 60, },
				{ name = "chair61", price = 0, amount = 50, info = {}, type = "item", slot = 61, },
				{ name = "chair62", price = 0, amount = 50, info = {}, type = "item", slot = 62, },
				{ name = "chair63", price = 0, amount = 50, info = {}, type = "item", slot = 63, },
				{ name = "chair64", price = 0, amount = 50, info = {}, type = "item", slot = 64, },
				{ name = "chair65", price = 0, amount = 50, info = {}, type = "item", slot = 65, },
				{ name = "chair66", price = 0, amount = 50, info = {}, type = "item", slot = 66, },
				{ name = "chair67", price = 0, amount = 50, info = {}, type = "item", slot = 67, },
				{ name = "chair68", price = 0, amount = 50, info = {}, type = "item", slot = 68, },
				{ name = "chair69", price = 0, amount = 50, info = {}, type = "item", slot = 69, },
				{ name = "chair70", price = 0, amount = 50, info = {}, type = "item", slot = 70, },
				{ name = "chair71", price = 0, amount = 50, info = {}, type = "item", slot = 71, },
				{ name = "chair72", price = 0, amount = 50, info = {}, type = "item", slot = 72, },
				{ name = "chair73", price = 0, amount = 50, info = {}, type = "item", slot = 73, },
				{ name = "chair74", price = 0, amount = 50, info = {}, type = "item", slot = 74, },
				{ name = "chair75", price = 0, amount = 50, info = {}, type = "item", slot = 75, },
				{ name = "chair76", price = 0, amount = 50, info = {}, type = "item", slot = 76, },
				{ name = "chair77", price = 0, amount = 50, info = {}, type = "item", slot = 77, },
				{ name = "chair78", price = 0, amount = 50, info = {}, type = "item", slot = 78, },
				{ name = "chair79", price = 0, amount = 50, info = {}, type = "item", slot = 79, },
				{ name = "chair80", price = 0, amount = 50, info = {}, type = "item", slot = 80, },
				{ name = "chair81", price = 0, amount = 50, info = {}, type = "item", slot = 81, },
				{ name = "chair82", price = 0, amount = 50, info = {}, type = "item", slot = 82, },
				{ name = "chair83", price = 0, amount = 50, info = {}, type = "item", slot = 83, },
				{ name = "chair84", price = 0, amount = 50, info = {}, type = "item", slot = 84, },
				{ name = "chair85", price = 0, amount = 50, info = {}, type = "item", slot = 85, },
				{ name = "chair86", price = 0, amount = 50, info = {}, type = "item", slot = 86, },
				{ name = "chair87", price = 0, amount = 50, info = {}, type = "item", slot = 87, },
				{ name = "chair88", price = 0, amount = 50, info = {}, type = "item", slot = 88, },
				{ name = "chair89", price = 0, amount = 50, info = {}, type = "item", slot = 89, },
				{ name = "chair90", price = 0, amount = 50, info = {}, type = "item", slot = 90, },
				{ name = "chair91", price = 0, amount = 50, info = {}, type = "item", slot = 91, },
				{ name = "chair92", price = 0, amount = 50, info = {}, type = "item", slot = 92, },
				{ name = "chair93", price = 0, amount = 50, info = {}, type = "item", slot = 93, },
				{ name = "chair94", price = 0, amount = 50, info = {}, type = "item", slot = 94, },
				{ name = "chair95", price = 0, amount = 50, info = {}, type = "item", slot = 95, },
				{ name = "chair96", price = 0, amount = 50, info = {}, type = "item", slot = 96, },
				{ name = "chair97", price = 0, amount = 50, info = {}, type = "item", slot = 97, },
				{ name = "chair98", price = 0, amount = 50, info = {}, type = "item", slot = 98, },
				{ name = "chair99", price = 0, amount = 50, info = {}, type = "item", slot = 99, },
				{ name = "chair100", price = 0, amount = 50, info = {}, type = "item", slot = 100, },
				{ name = "chair101", price = 0, amount = 50, info = {}, type = "item", slot = 101, },
				{ name = "chair102", price = 0, amount = 50, info = {}, type = "item", slot = 102, },
				{ name = "chair103", price = 0, amount = 50, info = {}, type = "item", slot = 103, },
				{ name = "chair104", price = 0, amount = 50, info = {}, type = "item", slot = 104, },
				{ name = "chair105", price = 0, amount = 50, info = {}, type = "item", slot = 105, },
				{ name = "chair106", price = 0, amount = 50, info = {}, type = "item", slot = 106, },
				{ name = "chair107", price = 0, amount = 50, info = {}, type = "item", slot = 107, },
				{ name = "chair108", price = 0, amount = 50, info = {}, type = "item", slot = 108, },
				{ name = "chair109", price = 0, amount = 50, info = {}, type = "item", slot = 109, },
				{ name = "chair110", price = 0, amount = 50, info = {}, type = "item", slot = 110, },
			},
			info = {
				coords = vector4(2746.19, 3469.28, 55.67, 243.34),
				showBlip = true,
				ped = {
					model = `S_M_Y_Construct_01`,
					scenario = "WORLD_HUMAN_CLIPBOARD",
				},
			},
		},
		
	}
}